[package]
name = "pokemonle-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
darling = { version = "^0.20" }
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
