[package]
name = "pokemonle-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
pokemonle-trait = { path = "../pokemonle-trait" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
diesel = { version = "^2.2", features = [
    "postgres",
    "sqlite",
    "chrono",
    "r2d2",
    "numeric",
] }
diesel_migrations = { version = "^2.2", features = ["postgres", "sqlite"] }
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
dotenvy = "^0.15.0"
schemars = { version = "0.8", features = ["derive"] }
aide = { version = "^0.14", features = ["macros"] }
